version: '2'
services:
  acmedates-app:
    image: acmedates
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://acmedates-postgresql:5432/AcmeDates
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  acmedates-postgresql:
    extends:
      file: docker-compose.yml
      service: acmedates-postgresql
