version: '2'
services:
  acmedates-postgresql:
    image: postgres:11.6
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=d8StezT
      - POSTGRES_DB=AcmeDates
    ports:
      - 5432:5432

volumes:
  database_data:
    driver: local
